server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb+srv://campushareAdmin:campusharePassword@clustercampushare.qhbomhf.mongodb.net/?retryWrites=true&w=majority
      database: PostDB
  kafka:
    bootstrap-servers: 35.219.146.212:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      create-post-topic-name: create_post_topic
      edit-post-topic-name: edit_post_topic
